# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-14 19:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_eventspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(verbose_name="Event's date")),
                ('topicTag', models.CharField(max_length=25)),
                ('name', models.CharField(max_length=50)),
                ('place', models.CharField(max_length=40)),
            ],
        ),
    ]
