# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 07:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='city',
            field=models.CharField(default='Where it is', max_length=20),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='hour_end',
            field=models.PositiveSmallIntegerField(default='23'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='hour_start',
            field=models.PositiveSmallIntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='main_title',
            field=models.CharField(default='Event Description', max_length=75),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='main_title_link',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='min_end',
            field=models.PositiveSmallIntegerField(default='59'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='min_start',
            field=models.PositiveSmallIntegerField(default='00'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='place_link',
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='place',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
