# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0007_eventsrelatedlink'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsrelatedlink',
            old_name='title',
            new_name='titles',
        ),
        migrations.AlterField(
            model_name='eventsrelatedlink',
            name='link_external',
            field=models.URLField(blank=True, help_text='Set an external link if you want to describe the event from an other web site', null=True, verbose_name='External link'),
        ),
        migrations.AlterField(
            model_name='eventsrelatedlink',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Choose an existing page (event must have already been created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailcore.Page'),
        ),
    ]
