# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 10:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0008_auto_20160115_1053'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eventsrelatedlink',
            old_name='titles',
            new_name='title',
        ),
    ]
