# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-15 15:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_auto_20160115_1054'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Event',
        ),
    ]
