# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-16 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_delete_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspage',
            name='hour_end',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='hour_start',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='min_end',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='min_start',
        ),
        migrations.RemoveField(
            model_name='eventspage',
            name='name',
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='city',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='main_title',
            field=models.CharField(default='Event Description', max_length=255),
        ),
        migrations.AlterField(
            model_name='eventsrelatedlink',
            name='link_page',
            field=models.ForeignKey(blank=True, help_text='Choose an existing page (event must have already been created)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='home.EventsPage'),
        ),
    ]
