# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0012_remove_eventsrelatedlink_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventspage',
            name='date',
        ),
        migrations.AddField(
            model_name='eventspage',
            name='date_start',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 17, 13, 43, 31, 499979)),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='date_stop',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2016, 1, 17, 13, 43, 31, 500023)),
        ),
    ]
