# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-17 13:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0013_auto_20160117_1343'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='date_start',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='eventspage',
            name='date_stop',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now),
        ),
    ]
