# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-18 21:54
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.blocks
import wagtail.wagtailcore.fields
import wagtail.wagtailimages.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0016_auto_20160118_1312'),
    ]

    operations = [
        migrations.AddField(
            model_name='homepage',
            name='image',
            field=wagtail.wagtailcore.fields.StreamField([('name', wagtail.wagtailcore.blocks.CharBlock(help_text='title of your logo')), ('link', wagtail.wagtailcore.blocks.URLBlock(help_text='url to your website')), ('img', wagtail.wagtailimages.blocks.ImageChooserBlock())], blank=True),
        ),
    ]
