# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0018_logomaker'),
    ]

    operations = [
        migrations.AddField(
            model_name='logomaker',
            name='category',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='logomaker',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
