# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 08:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0019_auto_20160119_0835'),
    ]

    operations = [
        migrations.AlterField(
            model_name='logomaker',
            name='category',
            field=models.CharField(blank=True, help_text='for templating work choose "Organizer" or "Follower"', max_length=20),
        ),
    ]
