# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 13:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0022_auto_20160119_1250'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logomaker',
            old_name='logo',
            new_name='icon',
        ),
    ]
