# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 14:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0024_auto_20160119_1339'),
    ]

    operations = [
        migrations.RenameField(
            model_name='logomaker',
            old_name='mage',
            new_name='page',
        ),
    ]
