# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0025_auto_20160119_1415'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventspage',
            name='btn_link',
            field=models.URLField(default='http://www.open-source-innovation-spring.org'),
        ),
        migrations.AddField(
            model_name='eventspage',
            name='btn_txt',
            field=models.CharField(default='infos', max_length=30),
        ),
    ]
