# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-19 15:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0026_auto_20160119_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventspage',
            name='btn_txt',
            field=models.CharField(default="S'inscrire", max_length=30),
        ),
    ]
