# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 10:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0027_auto_20160119_1554'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='logomaker',
            name='category',
        ),
    ]
