# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-01-20 13:34
from __future__ import unicode_literals

from django.db import migrations
import wagtail.wagtailcore.fields


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0028_remove_logomaker_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventsrelatedlink',
            name='description',
            field=wagtail.wagtailcore.fields.RichTextField(blank=True, help_text='brief description of the event'),
        ),
    ]
